# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
      gradle(task: "clean")
      increment_version_name(
            app_project_dir: '**/app',
            bump_type: "#{ENV['BUMP_TYPE']}",
      )
      increment_version_code(app_project_dir: '**/app')
      gradle(
          task: 'assemble',
          build_type: 'Release',
          flavor: 'Dev'
      )
      firebase_app_distribution(
        app: "1:549333740165:android:50935888714c1ac0eb17ec",
        groups: "tsh",
        release_notes: "Lots of amazing new features to test out!",
        firebase_cli_token: "#{ENV['FIREBASE_CLI_TOKEN']}",
        firebase_cli_path: "/usr/local/bin/firebase"
      )
      gradle(
         task: 'bundle',
         build_type: 'Release',
         flavor: 'Dev'
        )
        upload_to_play_store(
          track: 'beta',
          skip_upload_apk: true,
        )
      git_commit(
        path: "./app/build.gradle",
        message: "ci: released new Android build: #{get_version_name(app_project_dir: '**/app')} [ci skip]"
      )
  end
end
